### os
FROM ubuntu:bionic
ENV DEBIAN_FRONTEND noninteractive

### apt
RUN apt-get -y update \
  && apt-get install -y --no-install-recommends --fix-missing \
  build-essential \
  cmake \
  unzip \
  zlib1g-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libbz2-dev \
  liblzma-dev \
  libcurl4-openssl-dev \
  default-jre \
  wget \
  git \
  python \
  python3.6 \
  python3-distutils \
  python3-setuptools


### Download, install programs

RUN mkdir /TOOLS

## wget

# pilon
RUN wget https://github.com/broadinstitute/pilon/releases/download/v1.23/pilon-1.23.jar -O /TOOLS/pilon-1.23.jar
ENV PATH "$PATH:/TOOLS/"

# SPAdes
RUN wget http://cab.spbu.ru/files/release3.14.0/SPAdes-3.14.0-Linux.tar.gz \
  && mkdir /TOOLS/spades \
  && tar -xzvf SPAdes-3.14.0-Linux.tar.gz -C /TOOLS/spades --strip-components 1 \
  && rm /SPAdes-3.14.0-Linux.tar.gz
ENV PATH "$PATH:/TOOLS/spades/bin"

# bowtie2
RUN wget https://github.com/BenLangmead/bowtie2/releases/download/v2.4.1/bowtie2-2.4.1-linux-x86_64.zip \
  && unzip bowtie2-2.4.1-linux-x86_64.zip -d /TOOLS \
  && rm /bowtie2-2.4.1-linux-x86_64.zip 
ENV PATH "$PATH:/TOOLS/bowtie2-2.4.1-linux-x86_64/"

# ncbi
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-x64-linux.tar.gz \
  && mkdir /TOOLS/ncbi-blast \
  && tar -xzvf ncbi-blast-2.10.0+-x64-linux.tar.gz -C /TOOLS/ncbi-blast --strip-components 1 \
  && rm /ncbi-blast-2.10.0+-x64-linux.tar.gz
ENV PATH "$PATH:/TOOLS/ncbi-blast/bin"

# samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 \
  && mkdir /TOOLS/samtools \
  && tar -xjf samtools-1.10.tar.bz2 -C /TOOLS/samtools --strip-components 1 \
  && cd /TOOLS/samtools/ && ./configure && make install \
  && rm /samtools-1.10.tar.bz2

## git clone

# racon
RUN git clone --recursive https://github.com/isovic/racon.git /TOOLS/racon \
  && mkdir /TOOLS/racon/build && cd /TOOLS/racon/build/ \
  && cmake -DCMAKE_BUILD_TYPE=Release .. && make && make install

# unicycler
RUN git clone https://github.com/rrwick/Unicycler.git /TOOLS/unicycler \
  && cd /TOOLS/unicycler && python3.6 setup.py install

### Setup directory structure
RUN mkdir /WORKSPACE
VOLUME /WORKSPACE
WORKDIR /WORKSPACE

